# Generated by Django 3.0.7 on 2020-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekta', '0002_url_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortLink',
            field=models.TextField(default=''),
        ),
    ]
