# Generated by Django 3.0.7 on 2020-06-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekta', '0003_url_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='numChrome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='numFirefox',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='numSafari',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='numberOfUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='numberOfVisits',
            field=models.IntegerField(default=0),
        ),
    ]
