# Generated by Django 3.0.7 on 2020-06-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekta', '0004_auto_20200617_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='numDesktop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='numMobile',
            field=models.IntegerField(default=0),
        ),
    ]
