# Generated by Django 3.0.7 on 2020-06-18 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yekta', '0006_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
