# Generated by Django 3.0.7 on 2020-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekta', '0007_auto_20200618_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
